### ISSUE TITLE
Проблема с полем 54-Ф3

### ISSUE THREAD

**Issue by b2z** [yandex-money/yandex-money-cms-joomla#5]
Скачал и установил новую версию 1.5.0. Захожу в настройки, включаю "Отправлять в Яндекс.Кассу данные для чеков (54-ФЗ)". Список отображается некорректно.

> Ставка в вашем магазине.
> 
> Слева — ставка НДС в вашем магазине, справа — в Яндекс.Кассе. Пожалуйста, сопоставьте их.
> $tax) { ?>
> % передавать в Яндекс.Кассу как

![default](https://user-images.githubusercontent.com/3051676/26893806-1fa61f3a-4bc5-11e7-96ec-772f3dcb1d98.png)

Посмотрел код. Вместо `<?php` используется `<?` - видимо из-за этого.

> PHP также допускает короткий открывающий тег <?, однако использовать их нежелательно, так как они доступны только если включены с помощью конфигурационной директивы php.ini short_open_tag, либо если PHP был сконфигурирован с опцией --enable-short-tags .

**Comment by actofgod** [comment]
исправлено в последней версии модуля
