### ISSUE TITLE
Заказ (Не закончен)

### ISSUE THREAD

**Issue by eugenystrigulin** [yandex-money/yandex-money-cms-joomla#8]
Установил JoomShopping 4.16
Установил Плагин Яндекс.Деньги Версия модуля 1.5.3
https://raw.githubusercontent.com/yandex-money/yandex-money-cms-joomla/master/YandexKassa.zip[/url])
настроил статус-оплачен

произвожу оплату, оплата проходит.
А в заказе на сайте статус (Не закончен).
Даже статус на оплачено(завершено) не меняется, значится в обработке
настроил Логи
error-пустой
payment-пустой
paymentdata-2018-03-05 09:41:22 url: /index.php/component/jshopping/checkout/step7?act=return&js_paymentclass=pm_yandexmoney&Itemid=0

https://fotki.yandex.ru/next/users/see-watson/album/210843/view/2325169[/url]
https://fotki.yandex.ru/next/users/see-watson/album/210843/view/2325170[/url]

**Comment by eugenystrigulin** [comment]
до чего дошол я :

посылаем
index.php?option=com_jshopping&controller=checkout&task=step7&act=notify&amp;js_paymentclass=pm_yandexmoney&amp;no_lang=1&amp;Itemid=0

получаем

/index.php/component/jshopping/checkout/step7?act=return&js_paymentclass=pm_yandexmoney&Itemid=0


??? куда делось act=notify&amp???

**Comment by ostulov** [comment]
Добрый день!
Спасибо за информацию, проверим.
